apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-nodeforgo
  labels:
    app: goweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goweb
  template:
    metadata:
      labels:
        app: goweb
    spec:
      containers:
      - name: mygocontainerforcrud
        image: rancherlxl/mygoforcrud:v2
        ports:
        containerPort: 8080
      imagePullSecrets:
       - name: myregistrykey
