apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-nodeforgo1
  labels:
    app: goweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goweb
  template:
    metadata:
      labels:
        app: goweb
    spec:
      containers:
      - name: mygocontainerforcrud
        image: rancherlxl/mygoforcrud:v3
        ports:
        containerPort: 9090
      imagePullSecrets:
       - name: myregistrykey
