apiVersion: v1

kind: Service

metadata:

  name: kube-node-serviceforgo

  labels:

    name: kube-node-serviceforgo

spec:

  type: NodePort      

  ports:

  - port: 80          
    targetPort: 9090  
    protocol: TCP

    nodePort: 32090   

  selector:

    app: goweb         

